# Generated by Django 5.0.2 on 2024-02-13 10:51

from django_ckeditor_5.fields import CKEditor5Field
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Klajdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klajdi_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mjeket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mjeket_image', models.ImageField(blank=True, upload_to='mjeket/')),
                ('mjeket_video', embed_video.fields.EmbedVideoField(blank=True)),
                ('mjeket_arsimi', CKEditor5Field(blank=True)),
                ('mjeket_punesimi', CKEditor5Field(blank=True)),
                ('departamenti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSalus.departamenti')),
            ],
        ),
        migrations.CreateModel(
            name='Specialitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialitet_image', models.ImageField(upload_to='specialitet')),
                ('specialitet_pershkrimi', CKEditor5Field(blank=True)),
                ('specialitet_serviset', CKEditor5Field(blank=True)),
                ('specialitet_video', embed_video.fields.EmbedVideoField(blank=True)),
                ('departamenti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSalus.departamenti')),
            ],
        ),
    ]
