# Generated by Django 5.0.2 on 2024-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_up', models.ImageField(upload_to='checkup')),
                ('check_name', models.CharField(max_length=100)),
            ],
        ),
    ]
