# Generated by Django 5.0.2 on 2024-02-14 09:16

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0002_checkup'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(upload_to='aboutus')),
                ('about_pershkrimi', CKEditor5Field(blank=True)),
                ('about_oltipershkrimi', CKEditor5Field(blank=True)),
                ('about_imgambjeti', models.ImageField(upload_to='aboutus')),
            ],
        ),
    ]
