# Generated by Django 5.0.2 on 2024-02-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_img', models.ImageField(upload_to='foto_ambjete')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='about_imgambjeti',
            field=models.ImageField(blank=True, upload_to='aboutus'),
        ),
    ]
