# Generated by Django 5.0.2 on 2024-02-19 09:48

import ckeditor.fields
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0004_foto_alter_about_about_imgambjeti'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlinikaFerti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klinika_name', models.CharField(blank=True, max_length=100, null=True)),
                ('klinika_img', models.ImageField(blank=True, null=True, upload_to='klinikafer')),
                ('klinika_description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='about_imgambjeti',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_oltipershkrimi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_pershkrimi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='check_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='check_up',
            field=models.ImageField(blank=True, null=True, upload_to='checkup'),
        ),
        migrations.AlterField(
            model_name='departamenti',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto_img',
            field=models.ImageField(blank=True, null=True, upload_to='foto_ambjete'),
        ),
        migrations.AlterField(
            model_name='klajdi',
            name='klajdi_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='departamenti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSalus.departamenti'),
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='mjeket_arsimi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='mjeket_image',
            field=models.ImageField(blank=True, null=True, upload_to='mjeket/'),
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='mjeket_punesimi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='mjeket_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialitet',
            name='departamenti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSalus.departamenti'),
        ),
        migrations.AlterField(
            model_name='specialitet',
            name='specialitet_image',
            field=models.ImageField(blank=True, null=True, upload_to='specialitet'),
        ),
        migrations.AlterField(
            model_name='specialitet',
            name='specialitet_pershkrimi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialitet',
            name='specialitet_serviset',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialitet',
            name='specialitet_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
