# Generated by Django 5.0.2 on 2024-02-21 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0006_aemc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aemc',
            name='AeMC_CV',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
