# Generated by Django 5.0.2 on 2024-02-21 12:00

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0006_aemc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aemc',
            name='AeMC_CV',
            field=CKEditor5Field(blank=True, null=True),
        ),
    ]
