# Generated by Django 5.0.2 on 2024-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0007_aemc_aemc_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
