# Generated by Django 5.0.2 on 2024-03-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0008_specialitet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialitet',
            old_name='name',
            new_name='specialitet_name',
        ),
    ]
