# Generated by Django 5.0.2 on 2024-03-06 10:24

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0009_rename_name_specialitet_specialitet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitet',
            name='specialitet_name',
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video1',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video2',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
