# Generated by Django 5.0.2 on 2024-03-06 10:30

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0010_remove_specialitet_specialitet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video3',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video4',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video5',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video6',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video7',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialitet',
            name='specialitet_video8',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
