# Generated by Django 5.0.2 on 2024-04-05 11:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0012_artikujtinformues'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikujtinformuesAeMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artikujtinformuesAeMC/')),
                ('artAeMC', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
