# Generated by Django 5.0.2 on 2024-04-05 14:09

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0013_artikujtinformuesaemc'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikujtinformuesKartaInSalus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artikujtinformuesKartaInSalus/')),
                ('art_KartaInSalus', CKEditor5Field(blank=True, null=True)),
            ],
        ),
    ]
