# Generated by Django 5.0.2 on 2024-04-08 09:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0014_artikujtinformueskartainsalus'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikujtinformuesDonnaSalus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artikujtinformuesDonnaSalus/')),
                ('art_DonnaSalus', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
