# Generated by Django 5.0.2 on 2024-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0015_artikujtinformuesdonnasalus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('age_choice', models.CharField(blank=True, choices=[('Nën 18 vjeç', 'Nën 18 vjeç'), ('18-40', '18-40'), ('Mbi 40 vjeç', 'Mbi 40 vjeç')], max_length=50, null=True)),
                ('gender_choice', models.CharField(blank=True, choices=[('Mashkull', 'Mashkull'), ('Femër', 'Femër')], max_length=50, null=True)),
            ],
        ),
    ]
