# Generated by Django 5.0.2 on 2024-04-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0017_contact_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klajdi',
        ),
    ]
