# Generated by Django 5.0.2 on 2024-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0018_delete_klajdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
