# Generated by Django 5.0.2 on 2024-04-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0019_alter_contact_age_choice_alter_contact_gender_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt_Salus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
