# Generated by Django 5.0.2 on 2024-04-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0021_linitakim_salus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiniTakim_salus',
        ),
    ]
