# Generated by Django 5.0.2 on 2024-04-13 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0024_specialitet_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikujtinformues',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='artikujtinformuesaemc',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='artikujtinformuesdonnasalus',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='artikujtinformueskartainsalus',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='checkup',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='artikujtinformues',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artikujtinformuesdonnasalus',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkup',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
