# Generated by Django 5.0.2 on 2024-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0025_alter_artikujtinformues_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linitakim_salus',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
