# Generated by Django 5.0.2 on 2024-04-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0026_alter_linitakim_salus_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontakt_salus',
            old_name='name',
            new_name='fullname',
        ),
    ]
