# Generated by Django 5.0.2 on 2024-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0027_rename_name_kontakt_salus_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontact_Salus_Tirana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
