# Generated by Django 5.0.2 on 2024-04-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0029_kontact_salus_laborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linitakim_salus',
            old_name='age',
            new_name='mjeku',
        ),
        migrations.RenameField(
            model_name='linitakim_salus',
            old_name='date',
            new_name='specialiteti',
        ),
        migrations.RemoveField(
            model_name='linitakim_salus',
            name='gender',
        ),
    ]
