# Generated by Django 5.0.2 on 2024-04-23 13:22
from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0030_rename_age_linitakim_salus_mjeku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikujtinformueskartainsalus',
            name='art_KartaInSalus',
            field=CKEditor5Field(blank=True, null=True, verbose_name='Art_KIS'),
        ),
        migrations.AlterField(
            model_name='artikujtinformueskartainsalus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
