# Generated by Django 5.0.2 on 2024-04-23 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0031_alter_artikujtinformueskartainsalus_art_kartainsalus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='art_KartaInSalus_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Art_KIS'),
        ),
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='art_KartaInSalus_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Art_KIS'),
        ),
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='art_KartaInSalus_sq',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Art_KIS'),
        ),
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='name_it',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='artikujtinformueskartainsalus',
            name='name_sq',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
