# Generated by Django 5.0.2 on 2024-04-24 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0034_remove_artikujtinformuesaemc_artaemc_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikujtinformueskartainsalus',
            name='art_KartaInSalus',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='art_KartaInSalus'),
        ),
        migrations.AlterField(
            model_name='artikujtinformueskartainsalus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
