# Generated by Django 5.0.2 on 2024-04-29 07:19

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0036_remove_artikujtinformueskartainsalus_art_kartainsalus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamenti',
            options={'verbose_name': 'departamenti', 'verbose_name_plural': 'departamentet'},
        ),
        migrations.RemoveField(
            model_name='departamenti',
            name='name',
        ),
        migrations.CreateModel(
            name='DepartamentiTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='appSalus.departamenti')),
            ],
            options={
                'verbose_name': 'departamenti Translation',
                'db_table': 'appSalus_departamenti_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
