# Generated by Django 5.0.2 on 2024-05-01 12:28

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0038_remove_artikujtinformues_art_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mjeket',
            name='mjeket_arsimi',
        ),
        migrations.RemoveField(
            model_name='mjeket',
            name='mjeket_punesimi',
        ),
        migrations.RemoveField(
            model_name='mjeket',
            name='name',
        ),
        migrations.AlterField(
            model_name='mjeket',
            name='departamenti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mjeket_departamenti', to='appSalus.departamenti'),
        ),
        migrations.CreateModel(
            name='MjeketTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('mjeket_arsimi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='mjeket_arsimi')),
                ('mjeket_punesimi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='mjeket_punesimi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='appSalus.mjeket')),
            ],
            options={
                'verbose_name': 'mjeket Translation',
                'db_table': 'appSalus_mjeket_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
