# Generated by Django 5.0.2 on 2024-05-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0039_remove_mjeket_mjeket_arsimi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitet',
            name='departamenti',
        ),
    ]
