# Generated by Django 5.0.2 on 2024-05-06 11:16

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0042_remove_aemc_aemc_cv_remove_aemc_aemc_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikujtinformuesaemc',
            name='artAeMC',
        ),
        migrations.RemoveField(
            model_name='artikujtinformuesaemc',
            name='name',
        ),
        migrations.CreateModel(
            name='artikujtinformuesAeMCTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('artAeMC', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='appSalus.artikujtinformuesaemc')),
            ],
            options={
                'verbose_name': 'artikujtinformues ae mc Translation',
                'db_table': 'appSalus_artikujtinformuesaemc_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
