# Generated by Django 5.0.2 on 2024-05-07 08:00

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0045_remove_klinikaferti_klinika_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specialitet',
            name='specialitet_pershkrimi',
        ),
        migrations.RemoveField(
            model_name='specialitet',
            name='specialitet_serviset',
        ),
        migrations.CreateModel(
            name='SpecialitetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('specialitet_pershkrimi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('specialitet_serviset', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='appSalus.specialitet')),
            ],
            options={
                'verbose_name': 'specialitet Translation',
                'db_table': 'appSalus_specialitet_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
