# Generated by Django 5.0.2 on 2024-05-10 07:28

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0046_remove_specialitet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='artAeMC_video1',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='artAeMC_video2',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='artAeMC_video3',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='artAeMC_video4',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='artAeMC_video5',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikujtinformuesaemc',
            name='artAeMC_video6',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
