# Generated by Django 5.0.2 on 2024-05-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0050_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Video_AlbaNostra',
        ),
    ]
