# Generated by Django 5.0.2 on 2024-05-23 09:35

from django_ckeditor_5.fields import CKEditor5Field
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0051_rename_video_video_albanostra'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikujtinformuesAlbaNostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artikujtinformuesAlbaNostra/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='artikujtinformuesAlbaNostraTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('art_description', CKEditor5Field(blank=True, null=True, verbose_name='art_description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='appSalus.artikujtinformuesalbanostra')),
            ],
            options={
                'verbose_name': 'artikujtinformues alba nostra Translation',
                'db_table': 'appSalus_artikujtinformuesalbanostra_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
