# Generated by Django 5.0.2 on 2024-06-03 12:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0053_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='about_oltipershkrimi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouttranslation',
            name='about_pershkrimi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aemctranslation',
            name='AeMC_CV',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aemctranslation',
            name='AeMC_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikujtinformuesaemctranslation',
            name='artAeMC',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikujtinformuesalbanostratranslation',
            name='art_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='art_description'),
        ),
        migrations.AlterField(
            model_name='artikujtinformuesdonnasalustranslation',
            name='art_DonnaSalus',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikujtinformueskartainsalustranslation',
            name='art_KartaInSalus',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='art_KartaInSalus'),
        ),
        migrations.AlterField(
            model_name='artikujtinformuestranslation',
            name='art_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='art_description'),
        ),
        migrations.AlterField(
            model_name='klinikafertitranslation',
            name='klinika_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mjekettranslation',
            name='mjeket_arsimi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='mjeket_arsimi'),
        ),
        migrations.AlterField(
            model_name='mjekettranslation',
            name='mjeket_punesimi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='mjeket_punesimi'),
        ),
        migrations.AlterField(
            model_name='specialitettranslation',
            name='specialitet_pershkrimi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialitettranslation',
            name='specialitet_serviset',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
