# Generated by Django 5.0.2 on 2024-08-22 10:49

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0054_alter_abouttranslation_about_oltipershkrimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbaNostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlbaNostraTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('AeMC_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='appSalus.albanostra')),
            ],
            options={
                'verbose_name': 'alba nostra Translation',
                'db_table': 'appSalus_albanostra_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
