# Generated by Django 5.0.2 on 2024-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0056_rename_aemc_text_albanostratranslation_albanostra_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkup_albanostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_albanostra', models.ImageField(blank=True, null=True, upload_to='checkup_albanostra')),
            ],
        ),
    ]
